import Link from"next/link";import{notFound,redirect}from"next/navigation";import{db}from"@/lib/db";import{getSession}from"@/lib/auth";import{saveMilestone,deleteMilestone,saveRequirement,deleteRequirement}from"./actions";
const date=(v:any)=>v?new Date(v).toISOString().slice(0,10):"",display=(v:any)=>v?new Date(v).toLocaleDateString("en",{day:"numeric",month:"short",year:"numeric"}):"Not set";
export default async function Structure({params}:{params:Promise<{id:string}>}){
 const s=await getSession();if(!s)redirect("/login");const{id}=await params;
 const access=await db.query("select p.name from projects p join project_members pm on pm.project_id=p.id where p.id=$1 and pm.user_id=$2 and pm.role in ('OWNER','MANAGER')",[id,s.userId]);if(!access.rowCount)notFound();
 const ms=(await db.query("select * from milestones where project_id=$1 order by position",[id])).rows,rs=(await db.query("select * from requirements where project_id=$1 order by position",[id])).rows,count=(mid:string)=>rs.filter(x=>x.milestone_id===mid).length;
 return <main className="project-page structure-page">
  <div className="project-top"><Link href={`/projects/${id}`}>← Project overview</Link><Link href={`/projects/${id}/manage`} className="primary">＋ Add to roadmap</Link></div>
  <section className="structure-hero"><div><p className="eyebrow">ROADMAP STRUCTURE</p><h1>{access.rows[0].name}</h1><p>Organize delivery milestones and the requirements inside each stage.</p></div><div className="structure-stats"><span><strong>{ms.length}</strong> Milestones</span><span><strong>{rs.length}</strong> Requirements</span><span><strong>{rs.filter(x=>x.status==="DONE").length}</strong> Completed</span></div></section>
  <section className="structure-section"><div className="structure-heading"><div><p className="eyebrow">DELIVERY STAGES</p><h2>Milestones</h2></div><small>Edit titles, dates and status.</small></div><div className="milestone-card-grid">{ms.map(m=><article className="structure-card milestone-structure-card" key={m.id}>
   <div className="structure-number">S{m.position}</div><div className="structure-card-copy"><div><strong>{m.title}</strong><em className={`structure-status ${m.status.toLowerCase()}`}>{m.status.replaceAll("_"," ")}</em></div><p>{display(m.starts_on)} → {display(m.due_on)}</p><small>{count(m.id)} functional requirements</small></div>
   <form action={saveMilestone} className="login-form structure-edit-form"><h2>Edit milestone</h2><p className="modal-intro">Update <strong>{m.title}</strong>.</p><input type="hidden" name="project" value={id}/><input type="hidden" name="id" value={m.id}/><label>Title<input name="title" defaultValue={m.title} required/></label><div className="form-grid"><label>Start date<input name="starts_on" type="date" defaultValue={date(m.starts_on)}/></label><label>Due date<input name="due_on" type="date" defaultValue={date(m.due_on)}/></label></div><label>Status<select name="status" defaultValue={m.status}><option value="UPCOMING">Upcoming</option><option value="ACTIVE">Active</option><option value="BLOCKED">Blocked</option><option value="DONE">Done</option></select></label><button className="primary">Save milestone</button><button formAction={deleteMilestone} name="confirm" value="yes" className="delete-inline">Delete milestone if empty</button></form>
  </article>)}</div></section>
  <section className="structure-section"><div className="structure-heading"><div><p className="eyebrow">PROJECT SCOPE</p><h2>Functional requirements</h2></div><small>Grouped by milestone.</small></div><div className="requirement-groups">{ms.map(m=>{const items=rs.filter(x=>x.milestone_id===m.id);return <section className="requirement-group" key={m.id}>
   <header><span>S{m.position}</span><div><strong>{m.title}</strong><small>{items.length} requirements</small></div></header><div>{items.length?items.map(r=><article className="requirement-structure-card" key={r.id}>
    <span>{r.code}</span><div><strong>{r.title}</strong><small>{r.description||"No description added"}</small></div><em className={`structure-status ${r.status.toLowerCase()}`}>{r.status.replaceAll("_"," ")}</em>
    <form action={saveRequirement} className="login-form structure-edit-form"><h2>Edit requirement</h2><p className="modal-intro">Move, rename or update this requirement.</p><input type="hidden" name="project" value={id}/><input type="hidden" name="id" value={r.id}/><label>Milestone<select name="milestone" defaultValue={r.milestone_id}>{ms.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><div className="form-grid"><label>Code<input name="code" defaultValue={r.code} required/></label><label>Status<select name="status" defaultValue={r.status}><option value="NOT_STARTED">Not started</option><option value="IN_PROGRESS">In progress</option><option value="BLOCKED">Blocked</option><option value="DONE">Done</option></select></label></div><label>Title<input name="title" defaultValue={r.title} required/></label><label>Description<textarea name="description" defaultValue={r.description||""}/></label><button className="primary">Save requirement</button><button formAction={deleteRequirement} name="confirm" value="yes" className="delete-inline">Delete requirement if empty</button></form>
   </article>):<div className="requirement-empty">No requirements in this milestone.</div>}</div>
  </section>})}</div></section>
 </main>
}
