import"server-only";import nodemailer from"nodemailer";import{db}from"@/lib/db";import{sendReportMessage}from"@/lib/evolution";import{reportEmail,deliveryFailureEmail}from"@/lib/report-email";
const transport=()=>nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||465),secure:process.env.SMTP_SECURE==="true",auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASSWORD}});
// Tell the people who can act on it. Swallows everything: an alert that fails must
// not mask the delivery failure it reports, and a dead SMTP host would otherwise
// throw here on its way out of the catch below.
async function alertManagers(delivery:any,reason:string){try{
 const managers=(await db.query("select u.full_name,u.email,u.locale from project_members pm join users u on u.id=pm.user_id where pm.project_id=$1 and pm.role='MANAGER' and u.is_active",[delivery.project_id])).rows;
 if(!managers.length)return;
 const mailer=transport();
 for(const manager of managers){const mail=deliveryFailureEmail({appUrl:String(process.env.APP_URL||""),managerName:manager.full_name,projectName:delivery.project_name,reportTitle:delivery.title,clientName:delivery.full_name,channel:delivery.channel,reason,locale:manager.locale});await mailer.sendMail({from:process.env.SMTP_USER,to:manager.email,subject:mail.subject,text:mail.text,html:mail.html})}
}catch{}}
export async function deliverNotification(deliveryId:string){const delivery=(await db.query(`select nd.id,nd.channel,nd.report_id,r.project_id,u.email,u.phone,u.full_name,u.locale,u.whatsapp_opt_in,r.title,p.name project_name from notification_deliveries nd join users u on u.id=nd.recipient_id join reports r on r.id=nd.report_id join projects p on p.id=r.project_id where nd.id=$1`,[deliveryId])).rows[0];if(!delivery)throw new Error("Delivery not found");const url=`${process.env.APP_URL}/reports/${delivery.report_id}`,projectUrl=`${process.env.APP_URL}/projects/${delivery.project_id}`,mail=reportEmail({appUrl:String(process.env.APP_URL||""),clientName:delivery.full_name,projectName:delivery.project_name,reportTitle:delivery.title,reportUrl:url,projectUrl,locale:delivery.locale});try{let result:any;if(delivery.channel==="email")result=await transport().sendMail({from:process.env.SMTP_USER,to:delivery.email,subject:mail.subject,text:mail.text,html:mail.html});else{if(!delivery.phone||!delivery.whatsapp_opt_in)throw new Error("WhatsApp is not enabled for this client");result=await sendReportMessage({phone:delivery.phone,clientName:delivery.full_name,projectName:delivery.project_name,reportTitle:delivery.title,reportUrl:url,projectUrl,locale:delivery.locale})}await db.query("update notification_deliveries set status='SENT',external_id=$1,error_message=null,sent_at=now(),updated_at=now() where id=$2",[result?.messageId||result?.key?.id||null,delivery.id]);return true}catch(error){const reason=error instanceof Error?error.message:"Delivery failed";await db.query("update notification_deliveries set status='FAILED',error_message=$1,updated_at=now() where id=$2",[reason,delivery.id]);await alertManagers(delivery,reason);return false}}
